### ISSUE TITLE
Windows test crashes

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-generator#4]
From https://github.com/elasticsearch/logstash/issues/2487

The tests, at least on windows, do something that cause rspec to crash out early before even running tests.

**Comment by ph** [comment]
fix is (https://github.com/logstash-plugins/logstash-input-generator/blob/master/lib/logstash/inputs/generator.rb#L51)

``` ruby
@host = Socket.gethostname.force_encoding(Encoding::UTF_8)
```

I am not a huge fan of monkey patching but I consider this a bug in jruby. :(
